# Generated by Django 5.0.1 on 2024-01-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="items",
        ),
        migrations.AddField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(to="items.tag"),
        ),
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
