# Generated by Django 5.0.2 on 2024-03-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_search_tag_created_at_tag_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='SearchLog',
        ),
    ]
